DROP TABLE IF EXISTS IMAGES;
CREATE TABLE IMAGES (
    ID INTEGER PRIMARY KEY,
    URL VARCHAR(60) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    ORDERING INTEGER NOT NULL DEFAULT 0,
    TYPE CHAR(3)
);

DROP TABLE IF EXISTS ITEMS;
CREATE TABLE ITEMS (
    ID INTEGER PRIMARY KEY,
    PARENT INTEGER NULL,
    ABSTRACT BOOLEAN NOT NULL DEFAULT FALSE,
    CUSTOMISATION BOOLEAN NOT NULL DEFAULT FALSE,
    TITLE VARCHAR(20) NOT NULL,
    BLURB VARCHAR(100) NULL,
    DESCRIPTION TEXT NULL,
    PRICE NUMERIC(8, 2) NOT NULL DEFAULT 0,
    WEIGHT FLOAT NOT NULL DEFAULT 0,
    IN_STOCK INTEGER NOT NULL DEFAULT 0,
    ON_BACKORDER INTEGER NOT NULL DEFAULT 0,
    CAN_BACKORDER BOOLEAN NOT NULL DEFAULT FALSE
);

DROP TABLE IF EXISTS PARTS;
CREATE TABLE PARTS (
    ID INTEGER PRIMARY KEY,
    TITLE VARCHAR(20) NOT NULL,
    BLURB VARCHAR(100) NULL,
    DESCRIPTION TEXT NULL,
    PRICE NUMERIC(8, 2) NOT NULL DEFAULT 0,
    WEIGHT FLOAT NOT NULL DEFAULT 0,
    IN_STOCK INTEGER NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS BATCHES;
CREATE TABLE BATCHES (
    ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    INITIAL_SIZE INTEGER NOT NULL DEFAULT 0,
    STARTED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE CUSTOMERS ();
DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS ();
DROP TABLE IF EXISTS IMAGES;
CREATE TABLE IMAGES ();
DROP TABLE IF EXISTS IMAGES;
CREATE TABLE IMAGES ();
DROP TABLE IF EXISTS IMAGES;
CREATE TABLE IMAGES ();
DROP TABLE IF EXISTS IMAGES;
CREATE TABLE IMAGES ();