DROP TABLE IF EXISTS order_product_boxes;
DROP TABLE IF EXISTS boxes;
DROP TYPE IF EXISTS BOX_STATUS;
DROP TABLE IF EXISTS order_products;
DROP TYPE IF EXISTS ORDER_PRODUCT_STATUS;
DROP TABLE IF EXISTS orders;
DROP TYPE IF EXISTS ORDER_STATUS;
