DROP TABLE IF EXISTS temp_user_roles;
DROP TABLE IF EXISTS temp_users;
DROP TYPE IF EXISTS TEMP_USER_STATUS;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS USER_STATUS;
DROP TABLE IF EXISTS roles;
