DROP TABLE IF EXISTS product_parts;
DROP TABLE IF EXISTS parts;
DROP TABLE IF EXISTS "batches";
DROP TABLE IF EXISTS products;
DROP TYPE IF EXISTS PRODUCT_STATUS;
DROP TABLE IF EXISTS categories;
DROP TYPE IF EXISTS CATEGORY_STATUS;
