DROP TABLE IF EXISTS part_images;
DROP TABLE IF EXISTS product_images;
DROP TABLE IF EXISTS category_images;
DROP TYPE IF EXISTS IMAGE_STATUS;
DROP TABLE IF EXISTS images;
DROP TYPE IF EXISTS MIMETYPE;
